# setup cmake env

# RXCW_CMAKE_DIR is the directory of RxCWCommon.cmake
set(RXCW_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR})

set(RXCW_ROOT_DIR ${RXCW_CMAKE_DIR}/..)
set(RXCW_INCLUDE_DIR ${RXCW_ROOT_DIR}/include)
set(RXCW_SOURCE_DIR ${RXCW_ROOT_DIR}/src)
set(RXCW_OUTPUT_DIR ${CMAKE_BINARY_DIR}/bin)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${RXCW_OUTPUT_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${RXCW_OUTPUT_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${RXCW_OUTPUT_DIR})
